# -*- coding: utf-8 -*-
"""Function_problem2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XRB10Bg9cObRGiThwQvGjqCFG-KxPXv1
"""

import random
import pandas as pd


def make_team(info):
    answ = []
    score = list(info.values())
    #### Your Code Here ####
    for i in range(len(score)):
      for j in range(i+1, len(score)):
        for k in range(j+1, len(score)):
            if score[i]+score[j]+score[k]>=50:
              answ.append((i, j, k))
    return answ




#### Do not edit here ####
with open('students.txt', 'r') as name_f: #이름이 저장된 파일 읽기
    student_list = name_f.readlines()
student_list = [n.rstrip('\n') for n in student_list]

cap = [-60, -15, 20, 20, 35, 40, 45, 50]
info = {}
for n, c in zip(student_list, cap):
    info[n] = c

info = {k: v for k, v in sorted(info.items(), key=lambda item: item[1])}
team = make_team(info)
student_list = list(info.keys())

print('=================Information================')
for i in range(len(cap)):
    if i%3==0:
        print('')
    print(f'{list(info.keys())[i]}:{list(info.values())[i]}', end='\t')
print('\n')
print('=================Possible Team List================')
print('')
for x,y,z in team:
    print(f'[ {student_list[x]}, {student_list[y]}, {student_list[z]} ]')